openapi: 3.0.0
info:
  title: openbanking-us
  description: "BNY API Example. Utilizing example spec from here: https://github.com/Mastercard/open-banking-us-openapi/tree/main"
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Charnley-Test/openbanking-us/1.0.0
  description: SwaggerHub API Auto Mocking
paths: {}
components: {}
